title: Ankit Gupta
url: "https://ankitg.me"
baseurl: "/"

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

markdown: kramdown
profile_picture: /assets/ankit.jpg
og_image: /assets/ankit.jpg

twitter_username: "@GuptaAnkitV"
tracking_id: UA-108355039-1

collections:
  - projects

paginate: false

sass:
    style: compressed
    sass_dir: _sass
