title: Ankit Gupta
url: "https://ankitvgupta.github.io"
baseurl: "/"

markdown: kramdown
twitter_username: GuptaAnkitV
tracking_id: UA-108355039-1

collections:
  - projects

paginate: false

sass:
    style: compressed
    sass_dir: _sass
